"""
FraudGraph — Fraud Monitoring Dashboard

An analyst-facing view of the fraud data: headline KPIs, where risk concentrates,
and the graph-detected candidate fraud rings.

Run:
    streamlit run dashboard/app.py
"""
import pandas as pd
import plotly.express as px
import streamlit as st
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

st.set_page_config(page_title="FraudGraph Dashboard", layout="wide", page_icon="🔎")


@st.cache_data
def load_data():
    df = pd.read_csv(ROOT / "data" / "fraud_sample.csv", parse_dates=["TransactionDate"])
    rings_path = ROOT / "data" / "fraud_rings.csv"
    rings = pd.read_csv(rings_path) if rings_path.exists() else pd.DataFrame()
    return df, rings


df, rings = load_data()

st.title("🔎 FraudGraph — Transaction Fraud Monitoring")
st.caption("IEEE-CIS Fraud Detection dataset (stratified sample) · SQL + graph-based analysis")

# ---------------- Sidebar filters ----------------
st.sidebar.header("Filters")
products = st.sidebar.multiselect(
    "Product category", sorted(df["ProductCD"].unique()), default=list(df["ProductCD"].unique())
)
devices = st.sidebar.multiselect(
    "Device type", sorted(df["DeviceType"].dropna().unique().tolist()) + ["unknown"],
    default=sorted(df["DeviceType"].dropna().unique().tolist()) + ["unknown"],
)

fdf = df[df["ProductCD"].isin(products)].copy()
fdf["DeviceType"] = fdf["DeviceType"].fillna("unknown")
fdf = fdf[fdf["DeviceType"].isin(devices)]

# ---------------- KPI row ----------------
total_txn = len(fdf)
fraud_txn = int(fdf["isFraud"].sum())
fraud_rate = (fraud_txn / total_txn * 100) if total_txn else 0
fraud_amt = fdf.loc[fdf.isFraud == 1, "TransactionAmt"].sum()
total_amt = fdf["TransactionAmt"].sum()
pct_dollars = (fraud_amt / total_amt * 100) if total_amt else 0

c1, c2, c3, c4 = st.columns(4)
c1.metric("Transactions", f"{total_txn:,}")
c2.metric("Fraud rate", f"{fraud_rate:.2f}%")
c3.metric("Dollars at risk", f"${fraud_amt:,.0f}")
c4.metric("% of volume at risk", f"{pct_dollars:.1f}%")

st.divider()

# ---------------- Charts ----------------
col1, col2 = st.columns(2)

with col1:
    st.subheader("Fraud rate by product category")
    prod = fdf.groupby("ProductCD").agg(n=("isFraud", "size"), fraud=("isFraud", "sum"))
    prod["fraud_rate_pct"] = (prod["fraud"] / prod["n"] * 100).round(2)
    fig = px.bar(prod.reset_index(), x="ProductCD", y="fraud_rate_pct",
                 color="fraud_rate_pct", color_continuous_scale="Reds",
                 labels={"fraud_rate_pct": "Fraud rate (%)", "ProductCD": "Product"})
    st.plotly_chart(fig, use_container_width=True)

with col2:
    st.subheader("Fraud rate by device type")
    dev = fdf.groupby("DeviceType").agg(n=("isFraud", "size"), fraud=("isFraud", "sum"))
    dev["fraud_rate_pct"] = (dev["fraud"] / dev["n"] * 100).round(2)
    fig = px.bar(dev.reset_index(), x="DeviceType", y="fraud_rate_pct",
                 color="fraud_rate_pct", color_continuous_scale="Oranges",
                 labels={"fraud_rate_pct": "Fraud rate (%)", "DeviceType": "Device"})
    st.plotly_chart(fig, use_container_width=True)

st.subheader("Fraud rate by hour of day")
hourly = fdf.groupby("TransactionHour").agg(n=("isFraud", "size"), fraud=("isFraud", "sum"))
hourly["fraud_rate_pct"] = (hourly["fraud"] / hourly["n"] * 100).round(2)
fig = px.line(hourly.reset_index(), x="TransactionHour", y="fraud_rate_pct", markers=True,
              labels={"fraud_rate_pct": "Fraud rate (%)", "TransactionHour": "Hour"})
fig.add_hline(y=fraud_rate, line_dash="dash", line_color="gray",
              annotation_text="overall avg")
st.plotly_chart(fig, use_container_width=True)

st.subheader("Transaction amount: fraud vs. legitimate")
trimmed = fdf[fdf.TransactionAmt < fdf.TransactionAmt.quantile(0.99)]
fig = px.box(trimmed, x="isFraud", y="TransactionAmt",
             labels={"isFraud": "0 = legitimate, 1 = fraud", "TransactionAmt": "Amount ($)"})
st.plotly_chart(fig, use_container_width=True)

st.divider()

# ---------------- Fraud rings ----------------
st.subheader("🕸️ Candidate fraud rings (graph-detected)")
st.caption(
    "Accounts connected via shared device fingerprints, grouped into clusters and "
    "ranked by fraud rate. Generated by graph/ring_detection.py — see graph/fraud_ring_queries.cypher "
    "for the equivalent Neo4j version."
)
if not rings.empty:
    top_rings = rings[rings.n_accounts >= 3].sort_values("fraud_rate_pct", ascending=False).head(10)
    st.dataframe(top_rings, use_container_width=True, hide_index=True)
else:
    st.info("Run `python graph/ring_detection.py` first to generate data/fraud_rings.csv.")

st.divider()
st.caption("Data: IEEE-CIS Fraud Detection (Kaggle) · Built for portfolio / data-analyst demonstration purposes.")
